server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.html;
    }

    # Backend dynamic routing (UAT or PROD)
    location /api/ {
        proxy_pass http://$BACKEND_HOST:$BACKEND_PORT;
    }
}
